---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: sausage-nginx
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    meta.helm.sh/release-namespace: "std-012-005"
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: sausage-store
    env: production 
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        server {

          listen       80;
          listen  [::]:80;
          server_name  localhost;

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              try_files $uri $uri/ /index.html;
          }
          location /api {
              proxy_pass http://backend:8080;
          }
        }
    }
