# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}-secret
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    meta.helm.sh/release-namespace: "std-012-005"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: production
data:
  DB: {{ .Values.data.DB }}
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    meta.helm.sh/release-namespace: "std-012-005"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: production
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
