# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: backendsec
  labels:
    app: backendsec
data:
  SPRING_DATASOURCE_USERNAME: bWVsb3VuODE1
  SPRING_DATASOURCE_PASSWORD: RGV2b3BzMTIzIQ==
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi1kZzNhM2tsdDRydDZrazQ3Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9tZWxvdW44MTU=
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL21lbG91bjgxNTpEZXZvcHMxMjMhQHJjMWEtZnRzcTgydW9sNHQ3bWNvcS5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L21lbG91bjgxNT90bHM9dHJ1ZQ==
  SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
#  vault_token: aHZzLkNBRVNJRnpBTkNHZEFJRUQ1cVk2ek0ya29ncnd1RkRTSVY5MXJBZjlXUWJUS0hJNUdoNEtIR2gyY3k0eFpGQktOVWxUVEVOMGRqQTRTMXBEWVV0YWEzRTJiRUU=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
