---
# tasks file for backend

- name: Install python3-lxml
  become: true
  apt:
    name: python3-lxml
    state: latest
    update_cache: yes

- name: Install openjdk-16
  become: true
  apt:
    name: openjdk-17-jdk
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add user
  become: true
  user:
    name: "{{ backend_service_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create dir for jar
  become: true
  ansible.builtin.file:
    path: "{{ backend_lib_directory }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: "{{ backend_service_user }}"
    group: "{{ backend_service_group }}"

- name: Create dir for reports
  become: true
  ansible.builtin.file:
    path: "{{ backend_report_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ backend_service_user }}"
    group: "{{ backend_service_group }}"

- name: Download artifact
  become: true
  maven_artifact:
    username: "{{ backend_nexus_login }}"
    password: "{{ backend_nexus_password }}"
    dest: "{{ backend_lib_directory }}sausage-store.jar"
    repository_url: "https://nexus.praktikum-services.ru/repository/sausage-store-oganov-alex-backend/"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "{{ backend_maven_version }}"

- name: Change file ownership, group and permissions
  become: true
  ansible.builtin.file:
    path: "{{ backend_lib_directory }}sausage-store.jar"
    owner: "{{ backend_service_user }}"
    group: "{{ backend_service_group }}"
    mode: 'u+rw,g-wx,o-wx'

- name: Chmod jar
  become: true
  file:
    dest: "{{ backend_lib_directory }}sausage-store.jar"
    mode: 'a+x'

- name: Temp conf
  become: true
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service

- name: Systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: Run SStore
  become: true
  service:
    name: sausage-store-backend
    state: restarted
