# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  DB: bW9uZ29kYjovL21lbG91bjgxNTpEZXZvcHMxMjMhQHJjMWEtZnRzcTgydW9sNHQ3bWNvcS5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L21lbG91bjgxNT90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQ==
#  vault_token: aHZzLkNBRVNJRnpBTkNHZEFJRUQ1cVk2ek0ya29ncnd1RkRTSVY5MXJBZjlXUWJUS0hJNUdoNEtIR2gyY3k0eFpGQktOVWxUVEVOMGRqQTRTMXBEWVV0YWEzRTJiRUU=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
